local T, C, L = unpack(select(2, ...)) -- Import: T - functions, constants, variables; C - config; L - locales
local TukuiWorldFrame = CreateFrame("Frame", nil, UIParent)
TukuiWorldFrame:RegisterEvent("PLAYER_ENTERING_WORLD")
-- create our moving area
local TukuiWorldFrameAnchor = CreateFrame("Button", "TukuiWorldFrameAnchor", UIParent)
TukuiWorldFrameAnchor:SetFrameStrata("TOOLTIP")
TukuiWorldFrameAnchor:SetFrameLevel(20)
TukuiWorldFrameAnchor:SetHeight(20)
TukuiWorldFrameAnchor:SetWidth(200)
TukuiWorldFrameAnchor:SetClampedToScreen(true)
TukuiWorldFrameAnchor:SetMovable(true)
TukuiWorldFrameAnchor:SetTemplate("Default")
TukuiWorldFrameAnchor:SetBackdropBorderColor(0,0,0,0)
TukuiWorldFrameAnchor:SetBackdropColor(0,0,0,0)
TukuiWorldFrameAnchor.text = T.SetFontString(TukuiWorldFrameAnchor, C["media"].font, 12)
TukuiWorldFrameAnchor.text:SetPoint("CENTER")
TukuiWorldFrameAnchor.text:SetText("Move WorldFrame")
TukuiWorldFrameAnchor.text:Hide()
TukuiWorldFrameAnchor:SetPoint("TOP", UIParent, "TOP", -50, -110)
TukuiWorldFrame:ClearAllPoints()
TukuiWorldFrame:SetParent(TukuiWorldFrameAnchor)
TukuiWorldFrame:SetPoint("BOTTOM")
TukuiWorldFrame:SetHeight(100)
TukuiWorldFrame:SetWidth(200)
WorldStateAlwaysUpFrame:ClearAllPoints()
WorldStateAlwaysUpFrame:SetParent(TukuiWorldFrame)
WorldStateAlwaysUpFrame:SetFrameStrata("MEDIUM")
WorldStateAlwaysUpFrame:SetFrameLevel(3)
WorldStateAlwaysUpFrame:SetClampedToScreen(true)
WorldStateAlwaysUpFrame:SetAllPoints()
WorldStateAlwaysUpFrame.SetPoint = T.dummy